main_project/blueprints/student/__init__.py
from .routes import student_bp

main_project/blueprints/student/routes.py
from flask import Flask, render_template, request, redirect, url_for, session, Blueprint,current_app,g
from flask_mysqldb import MySQL
from flask_bcrypt import Bcrypt
import random
from flask import session, redirect, url_for, render_template_string
from main_project import bcrypt
from sqlalchemy import create_engine, text
import datetime
import base64

from PIL import Image
from io import BytesIO

student_bp = Blueprint('student_bp', __name__,template_folder='templates',static_url_path='/static',static_folder='static')

@student_bp.before_request
def login_required():
    if 'email' not in session:
        # Redirect to the Google OAuth flow if the user is not authenticated
        return redirect(url_for('auth_bp.google',user_type='student'))



def get_db_connection():
    engine = create_engine('mysql://oceoAdmin:oceoAdmin@localhost/oceo_management')
    print("Engine created")
    return engine.connect()

def check_authorization(roll_number,job_id):
    cursor = get_db_connection()
    sql = f"SELECT * FROM application_status WHERE roll_number = {roll_number} AND job_id = {job_id};"
    result = cursor.execute(text(sql))
    cursor.close()
    if result.fetchone() is not None:
        return True
    else:
        return False
    



# ---------------------------------------------- STUDENT --------------------------------------------------------
@student_bp.route('', methods=['GET', 'POST']) # student homepage
def after_login_student():
    # db=get_db()
    if "roll_number" in session:

        # roll_number = session['roll_number']
        # studen_name = 
        if request.method == 'POST':
            testvar = request.form['submit_button']
            match testvar:
                case 'personal_info':
                    return redirect(url_for('student_bp.student_personal_info'))
                case 'jobs_available':
                    return redirect(url_for('student_bp.student_jobs_available'))
                case 'applied_jobs':
                    return redirect(url_for('student_bp.student_applied_jobs')) 
                case 'my_jobs':
                    return redirect(url_for('student_bp.student_my_jobs'))
                case 'logout':
                    return redirect(url_for('student_bp.logout'))
                case _:
                    return render_template('student/after_login.html')  
            
        cursor = get_db_connection()
        roll_number = session['roll_number']
        
        
      
        student_name = cursor.execute(text(f"SELECT first_name FROM applied_student WHERE roll_number = {roll_number};")).fetchone()[0]
        cursor.close()
        return render_template('student/after_login.html', student_name=student_name) # student homepage
    
    else:
        return redirect(url_for('auth_bp.errorpage', error_message="You are not authorised to view this page. Please login first."))

def phone_num_exist(roll_number):
    # db=get_db()
    cursor = get_db_connection()
    check_phone_query = f"SELECT count(*) FROM applied_student_phone WHERE roll_number = {roll_number};"
    
    phone_count = cursor.execute(text(check_phone_query)).fetchone()[0]
    cursor.close()
    return phone_count != 0

@student_bp.route('/personal_info', methods=['GET', 'POST'])
def student_personal_info():
    # db=get_db()
    if "roll_number" in session:
        if request.method == 'POST': 
            # profile update
            if request.form['submit_button'] == 'Update Profile': 
                return redirect(url_for('student_bp.student_personal_info_change'))
            elif request.form['submit_button'] == 'Change Password':
                return redirect(url_for('student_bp.change_password'))
            elif request.form['submit_button'] == 'Bank Details':
                return redirect(url_for('student_bp.student_bank_details'))

        cursor = get_db_connection()
        roll_number = session['roll_number']
        fetched_data =  cursor.execute(text(f"SELECT * FROM applied_student WHERE roll_number = '{roll_number}';")).fetchall()

        image_result=cursor.execute(text(f"SELECT person_img FROM applied_student WHERE roll_number = {roll_number};"))
        image_data = image_result.fetchone()[0]
        #convert the blob image data to base64
        image_data = base64.b64encode(image_data).decode('utf-8')

        # check if phone number exists
        if phone_num_exist(roll_number):
            # fetch existing phone numbers
            phone_query = f"SELECT phone_number,isMain FROM applied_student_phone WHERE roll_number = {roll_number};"
           
            
            fetched_phone = cursor.execute(text(phone_query)).fetchall()

        else:
            fetched_phone = ("Not Added", "Not Added")


        cursor.close()
        
        return render_template('student/personal_info.html', student_data=fetched_data, student_phone = fetched_phone, image_data=image_data)
    
    else:
        return redirect(url_for('auth_bp.errorpage'))

@student_bp.route('/personal_info/bank_details', methods=['GET', 'POST'])
def student_bank_details():
    # db=get_db()
    if "roll_number" in session:
        
        if request.method == 'POST':
            if request.form['submit_button'] == 'Edit':
                return redirect(url_for('student_bp.student_edit_bank_details'))

        cursor = get_db_connection()
        roll_number = session['roll_number']
        
        fetched_data = cursor.execute(text(f"SELECT bank_name, account_number, IFSC_code FROM bank_details WHERE roll_number = '{roll_number}';")).fetchall()
        cursor.close()  
        return render_template('student/bank_details.html', bank_data=fetched_data)
    else:
        return redirect(url_for('auth_bp.errorpage'))

@student_bp.route('/edit_bank_details', methods=['GET', 'POST'])
def student_edit_bank_details():
    # db=get_db()
    if "roll_number" in session:
        cursor = get_db_connection()
        
        bank_data = cursor.execute(text(f"SELECT * FROM bank_details WHERE roll_number = {session['roll_number']};")).fetchall()
        cursor.close()
        if request.method == 'POST':
            roll_number = session['roll_number']

            bank_name = request.form.get('bank_name')
            account_number = request.form.get('account_number')
            ifsc_code = request.form.get('ifsc_code')

            # --------------------
            cursor = get_db_connection()
          
            is_existing_roll_number =   cursor.execute(text(f"SELECT count(*) FROM bank_details WHERE roll_number = {roll_number};")).fetchone()[0]

            if is_existing_roll_number:
                update_query = f"UPDATE bank_details SET bank_name = '{bank_name}', account_number = {account_number}, IFSC_code = '{ifsc_code}' WHERE roll_number = {roll_number};"
                cursor.execute(text(update_query))
                cursor.commit()
            else:
                update_query = f"INSERT INTO bank_details (roll_number, bank_name, account_number, IFSC_code) VALUES ({roll_number}, '{bank_name}', {account_number}, '{ifsc_code}');"
                cursor.execute(text(f"INSERT INTO bank_details (roll_number, bank_name, account_number, IFSC_code) VALUES ({roll_number}, '{bank_name}', {account_number}, '{ifsc_code}');"))
                cursor.commit()
            # --------------------

           
            cursor.close()
            # return redirect(url_for('student_bank_details'))
            return redirect(url_for('student_bp.student_bank_details'))
            return render_template_string(f"""
                <script>
                    alert("Bank details updated successfully! Query Executed: {update_query}");
                    window.location.href = "{{{{ url_for('student_bank_details') }}}}";
                </script>
            """)
        return render_template('student/edit_bank_details.html', bank_data=bank_data)
    else:
        return redirect(url_for('auth_bp.errorpage'), error_message="You are not authorised to view this page. Please login first.")

# ---------------------------------------------------------------
def resize_image(image_data, max_size=(200, 200)):
    image = Image.open(BytesIO(image_data))
    image.thumbnail(max_size)  # Resize to max_size while maintaining aspect ratio
    
    output = BytesIO()
    if image.format == 'PNG':
        image = image.convert('RGB')  # Convert PNG to JPEG (no transparency support)
        image.save(output, format='JPEG', quality=100)  # Save as JPEG with quality compression (if required)
    else:
        image.save(output, format=image.format)  # Save other formats without conversion
    
    return output.getvalue()

# ---------------------------------------------------------------


@student_bp.route('/update_profile', methods=['GET', 'POST'])
def student_personal_info_change():
    # db=get_db()
    if "roll_number" in session:
        if request.method == 'POST':
            roll_number = session['roll_number']
            first_name = request.form.get('first_name')
            middle_name = request.form.get('middle_name')
            last_name = request.form.get('last_name')
            cpi = request.form.get('cpi')
            last_sem_spi = request.form.get('last_sem_spi')
            on_probation = 1 if request.form.get('on_probation') == 'Yes' else 0
            phone_1 = request.form.get('contact_number')
            phone_2 = request.form.get('alternate_contact_number')
            # fetch uploaded image
            cursor = get_db_connection()
            
            try:
                with cursor.begin():

                    cursor.execute(text(f"UPDATE applied_student SET first_name = '{first_name}', middle_name = '{middle_name}', last_name='{last_name}',cpi = {cpi}, last_sem_spi = {last_sem_spi}, on_probation = {on_probation} WHERE roll_number = {roll_number};"))
                    # cursor.commit()
                    if 'image' in request.files:

main_project/templates/student/after_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Login</title>
    <link rel="stylesheet" href="../../static/student/after_login.css">
</head>
<body>
    <header>
        <h1>Student Portal</h1>
        <!-- <img src="../../static/student/student.png" alt="student"> -->
        <img src="../../static/Final_IITGN-Logo-symmetric-Black.png" class="logo" alt="IITGN logo">
    </header>

    <form action="{{url_for('student_bp.after_login_student')}}" method="post">
        <div class="container">
            <h2>Welcome, {{student_name}}!</h2>
            <button class='btn' name="submit_button" value="personal_info" type="submit">Personal Information</button>
            <button class='btn' name="submit_button" value="jobs_available" type="submit">Jobs Available</button>
            <button class='btn' name="submit_button" value="applied_jobs" type="submit">Applied Jobs</button>
            <button class='btn' name="submit_button" value="my_jobs" type="submit">My Jobs</button>
            <button class='btn' name="submit_button" value="logout" type="submit">Logout</button>
        </div>
    </form>
    <footer>
        <p>&copy; 2024, DataWeavers, CS432 Databases, IIT Gandhinagar, Gujarat, India</p>
    </footer>
    <script src="../../static/student/after_login.js"></script>
</body>
</html>

main_project/templates/student/applied_jobs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Available Jobs</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/jobs_created.css">
</head>
<body>
    <!-- working student sidebar -->
    <div class="menu-icon" onclick="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
    </div>

    <div id="sidebar" class="sidebar">
        <h2>Dashboard</h2>
        <a href="/student">Home Page</a><br>
        <a href="/student/personal_info">Personal Info</a><br>
        
            <div class="sub-links">
                <a href="/student/personal_info">Personal Info Change</a><br>
                <a href="/student/personal_info/bank_details">Bank Details</a><br>
                <a href="/student/change_password">Change Password</a><br>
            </div>

        <a href="/student/applied_jobs">Applied Jobs</a><br>
        <a href="/student/jobs_available">Jobs Available</a><br>
        <a href="/student/my_jobs">My Jobs</a><br>
        <a href="/student/logout">Logout</a><br>
    </div>

    <div id="main-content-above" class="main-content-above">
        <!-- <p type="hidden">For space above the main form</p> -->
    </div>
    
    <div id="main-content" class="main-content table-container">
        <h1 class="main-content-heading">Applied Jobs</h1>
        <div class="table-container">
            <table class="main-content-table">
                <thead class="main-content-table-head">
                    <tr class="main-content-table-head-row">
                    {% for columnName in job_head %}
                        {% if columnName == "job_description" %}
                            <th><div style="width: 500px;">Job Description</div></th>
                        {% elif columnName == "additional_info" %}
                            <th><div style="width: 250px;">Additional Info</div></th>
                        {% elif columnName == "prerequisites"%}
                            <th><div style="width: 250px;">Prerequisites</div></th>
                        {% else %}
                            <th>{{ (columnName.replace("_", " ")).capitalize() }}</th>
                        {% endif %}
                    {% endfor %}
                    <th>Action button</th>
                    </tr>
                </thead>
                <tbody class="main-content-table-body">
                    {%set i = namespace(value=0)%}
                    {% for job in job_data %}
                        {% if i.value % 2 == 0 %}
                            <tr class="main-content-table-body-row">
                                {% for field in job %}
                                    <td><div class="scrollable-content" style="margin: 20px 0px 20px 0px;">{{ field }}</div></td>
                                {% endfor %}
                                <td>
                                    <form action="/student/applied_jobs" method="post">
                                        <input type="hidden" name="application_id" value="{{ job[0] }}">
                                        <button type="submit" class="update-profile" name="submit_button" value="cancel_application">Cancel</button>
                                    </form>
                                </td>
                            </tr>
                        {% else %}
                            <tr class="main-content-table-body-row" style="background-color: #e9e9e9;">
                                {% for field in job %}
                                    <td><div class="scrollable-content" style="margin: 20px 0px 20px 0px;">{{ field }}</div></td>
                                {% endfor %}
                                <td>
                                    <form action="/student/applied_jobs" method="post">
                                        <input type="hidden" name="application_id" value="{{ job[0] }}">
                                        <button type="submit" class="update-profile" name="submit_button" value="cancel_application">Cancel</button>
                                    </form>
                                </td>
                            </tr>
                        {% endif %}
                        {% set i.value = i.value + 1 %}
                        <!-- {% for field in job %}
                            <td><div class="scrollable-content" style="margin: 20px 0px 20px 0px;">{{ field }}</div></td>
                        {% endfor %} -->
                        <!-- <td>
                            <form action="/student/applied_jobs" method="post">
                                <input type="hidden" name="application_id" value="{{ job[0] }}">
                                <button type="submit" name="submit_button" value="cancel_application">Cancel Application</button>
                            </form>
                        </td> -->
                    <!-- </tr> -->

                    <!-- <tr class="main-content-table-body-row">
                        {% for field in job %}
                            <td><div class="scrollable-content" style="margin: 20px 0px 20px 0px;">{{ field }}</div></td>
                        {% endfor %}
                        <td>
                            <form action="/student/applied_jobs" method="post">
                                <input type="hidden" name="application_id" value="{{ job[0] }}">
                                <button type="submit" name="submit_button" value="cancel_application">Cancel Application</button>
                            </form>
                        </td>
                    </tr> -->
                    {% endfor %}
                </tbody>
            </table>
    </div>

    <!-- <table>
    <thead>
        <tr>
        {% for columnName in job_head %}
            <th>{{ columnName }}</th>
        {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for job in job_data %}
        <tr>
            {% for field in job %}
                <td>{{ field }}</td>
               
            {% endfor %}
            <td>
                <form action="/student/applied_jobs" method="post">
                    <input type="hidden" name="application_id" value="{{ job[0] }}">
                    <button type="submit" name="submit_button" value="cancel_application">Cancel Application</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table> -->

    <script>
        function toggleMenu() {
            var sidebar = document.getElementById('sidebar');
            var mainContent = document.getElementById('main-content');
            sidebar.classList.toggle('open');
        }
    </script>
    <script src="../../static/jobs_created.js"></script>

</body>
</html>

main_project/templates/student/apply_job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apply for a Job</title>

    <link rel="stylesheet" href="../../static/newuser.css">
    <!-- <link rel="stylesheet" href="../../static/login_page.css"> -->
    <!-- <link rel="stylesheet" href="../../static/personal_info.css"> -->
    <link rel="stylesheet" href="../../static/sidebar.css">
</head>
<body>
    <div id="student-sidebar">
        <!-- working student sidebar -->
        <div class="menu-icon" onclick="toggleMenu()">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <!-- student sidebar -->
        <div id="sidebar" class="sidebar">
            <h2>Dashboard</h2>
            <a href="/student">Home Page</a><br>
            <a href="/student/personal_info">Personal Info</a><br>
            <div class="sub-links">
                <a href="/student/personal_info">Personal Info Change</a><br>
                <a href="/student/personal_info/bank_details">Bank Details</a><br>
                <a href="/student/change_password">Change Password</a><br>
            </div>
            <a href="/student/applied_jobs">Applied Jobs</a><br>
            <a href="/student/jobs_available">Jobs Available</a><br>
            <a href="/student/my_jobs">My Jobs</a><br>
            <a href="/student/logout">Logout</a><br>
        </div>
    </div>

    <h1>Job Application</h1>
    <form action="/student/apply_job/{{job_id}}" method="post">
        
        <label for="job_id">Job:</label><br>
        <input type="text" id="job_id" name="job_id" value="{{job_id}}:{{job_role}}"  readonly><br>

        <label for="cpi">Current CPI:</label><br>
        <input type="text" id="cpi" name="cpi" required><br>

        <label for="last_sem_spi">Last Semester SPI:</label><br>
        <input type="text" id="last_sem_spi" name="last_sem_spi" required><br>

        <label for="statement_of_motivation">Statement of Motivation:</label><br>
        <textarea id="statement_of_motivation" name="statement_of_motivation" required></textarea><br>

        <input type="submit" id="submit-btn" value="Submit Application">
    </form>
    <script>
        function toggleSubmitButton() {            
            var cpi = document.getElementById("cpi").value.trim();
            var lastSemSPI = document.getElementById("last_sem_spi").value.trim();
            var statementOfMotivation = document.getElementById("statement_of_motivation").value.trim();

            var submitButton = document.getElementById("submit-btn");

            if (cpi && lastSemSPI && statementOfMotivation) {
                submitButton.classList.add("enabled");
            } else {
                submitButton.classList.remove("enabled");
            }
        }
        document.addEventListener("DOMContentLoaded", function() {
            var inputFields = document.querySelectorAll('input[type="text"], textarea');
            inputFields.forEach(function(field) {
                field.addEventListener("input", toggleSubmitButton);
            });
        });
    </script>
    <script src="../../static/sidebar.js"></script>
</body>
</html>

main_project/templates/student/bank_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/personal_info.css">
    <title>Bank details</title>
</head>
<body>
    <div class="menu-icon" onclick="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <!-- student sidebar -->
    <div id="sidebar" class="sidebar">
        <h2>Dashboard</h2>
        <a href="/student">Home Page</a><br>
        <a href="/student/personal_info">Personal Info</a><br>
        <div class="sub-links">
            <a href="/student/personal_info">Personal Info Change</a><br>
            <a href="/student/personal_info/bank_details">Bank Details</a><br>
            <a href="/student/change_password">Change Password</a><br>
        </div>
        <a href="/student/applied_jobs">Applied Jobs</a><br>
        <a href="/student/jobs_available">Jobs Available</a><br>
        <a href="/student/my_jobs">My Jobs</a><br>
        <a href="/student/logout">Logout</a><br>
    </div>
    <div id="main-content-above" class="main-content-above">
        <!-- <p type="hidden">For space above the main form</p> -->
    </div>
    <div id="main-content" class="main-content">
        <h1>Bank Details</h1>
        <table class="bank-details">
            <tr>
                <th>Bank Name</th>
                <th>Account Number</th>
                <th>IFSC Code</th>
            </tr>
            <tr>
                {% if bank_data %}
                    <td>{{ bank_data[0][0] }}</td>
                    <td>{{ bank_data[0][1] }}</td>
                    <td>{{ bank_data[0][2] }}</td>
                {% else %}
                    <td colspan="3">No bank details found</td>
                {% endif %}
            </tr>
        </table>
        <!-- redirect to ./edit_bank_details when the below form is submitted -->
        <form action="{{url_for('student_bp.student_edit_bank_details', bank_data = bank_data )}}" class="update-profile-form">
            <input type="submit" name="submit_button" value="Update Bank Details" class="update-profile">
        </form>
        <!-- <button onclick="window.location.href = '/student/edit_bank_details';" name="submit_button" value="Edit">Edit Bank Details</button> -->
    </div>
    <script src="../../static/personal_info.js"></script>
</body>
</html>

main_project/templates/student/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/personal_info.css">
</head>
<body>
    <div class="menu-icon" onclick="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <!-- student sidebar -->
    <div id="sidebar" class="sidebar">
        <h2>Dashboard</h2>
        <a href="/student">Home Page</a><br>
        <a href="/student/personal_info">Personal Info</a><br>
        <div class="sub-links">
            <a href="/student/personal_info">Personal Info Change</a><br>
            <a href="/student/personal_info/bank_details">Bank Details</a><br>
            <a href="/student/change_password">Change Password</a><br>
        </div>
        <a href="/student/applied_jobs">Applied Jobs</a><br>
        <a href="/student/jobs_available">Jobs Available</a><br>
        <a href="/student/my_jobs">My Jobs</a><br>
        <a href="/student/logout">Logout</a><br>
    </div>
    <div id="main-content-above" class="main-content-above">
        <!-- <p type="hidden">For space above the main form</p> -->
    </div>
    <div id="main-content" class="main-content">
        <form action="/student/change_password" method="post">
            <h1 class="main-content-heading">Change Password</h1>
            <label for="old_password">Old Password:</label><br>
            <input type="password" id="old_password" name="old_password" required><br>
            <label for="new_password">New Password:</label><br>
            <input type="password" id="new_password" name="new_password" required><br>
            <label for="confirm_password">Confirm Password:</label><br>
            <input type="password" id="confirm_password" name="confirm_password" required><br>
            <input type="submit" class="update-profile" value="Change Password">
        </form>
    </div>
    <script src="../../static/personal_info.js"></script>
</body>
</html>

main_project/templates/student/edit_bank_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Bank Details</title>
    <link rel="stylesheet" href="../../static/personal_info.css">
</head>
<body>
    <div class="menu-icon" onclick="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <!-- student sidebar -->
    <div id="sidebar" class="sidebar">
        <h2>Dashboard</h2>
        <a href="/student">Home Page</a><br>
        <a href="/student/personal_info">Personal Info</a><br>
        <div class="sub-links">
            <a href="/student/personal_info">Personal Info</a><br>
            <a href="/student/bank_details">Bank Details</a><br>
            <a href="/student/change_password">Change Password</a><br>
        </div>
        <a href="/student/applied_jobs">Applied Jobs</a><br>
        <a href="/student/jobs_available">Jobs Available</a><br>
        <a href="/student/my_jobs">My Jobs</a><br>
        <a href="/student/logout">Logout</a><br>
    </div>
    <div id="main-content-above" class="main-content-above">
        <!-- <p type="hidden">For space above the main form</p> -->
    </div>
    <div id="main-content" class="main-content">
        <h1 class="main-content-heading">Edit Bank Details</h1>
        <form action="/student/edit_bank_details" method="POST">
            <label for="bank_name">Bank Name:</label>
            <input type="text" id="bank_name" name="bank_name" value="{{bank_data[0][2]}}" required><br><br>
            <label for="account_number">Account Number:</label>
            <input type="text" id="account_number" name="account_number" value="{{bank_data[0][0]}}" required><br><br>
            <label for="ifsc_code">IFSC Code:</label>
            <input type="text" id="ifsc_code" name="ifsc_code" value="{{bank_data[0][1]}}" required><br><br>
            <input type="submit" class="update-profile" value="Submit">
        </form>
    </div>
    <script src="../../static/personal_info.js"></script>
</body>
</html>

main_project/templates/student/mentees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mentees</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/jobs_created.css">
</head>
<body>
    <!-- working student sidebar -->
    <div class="menu-icon" onclick="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <!-- student sidebar -->
    <div id="sidebar" class="sidebar">
        <h2>Dashboard</h2>
        <a href="/student">Home Page</a><br>
        <a href="/student/personal_info">Personal Info</a><br>
        <div class="sub-links">
            <a href="/student/personal_info">Personal Info Change</a><br>
            <a href="/student/personal_info/bank_details">Bank Details</a><br>
            <a href="/student/change_password">Change Password</a><br>
        </div>
        <a href="/student/applied_jobs">Applied Jobs</a><br>
        <a href="/student/jobs_available">Jobs Available</a><br>
        <a href="/student/my_jobs">My Jobs</a><br>
        <a href="/student/logout">Logout</a><br>
    </div>

    <div id="main-content-above" class="main-content-above">
        <!-- <p type="hidden">For space above the main form</p> -->
    </div>
    <div id="main-content" class="main-content table-container">
        <h1 class="main-content-heading">Mentees</h1>
        <div class="table-container">
            <table class="main-content-table">
                <thead class="main-content-table-head">
                    <tr class="main-content-table-head-row">
                    {% for columnName in mentee_head %}
                        <th>{{ columnName.replace("_", " ") }}</th>
                    {% endfor %}
                    </tr>
                </thead>
                <tbody class="main-content-table-body">
                    {% for job in mentee_data %}
                    <tr class="main-content-table-body-row">
                        {% for field in job %}
                            <td><div class="scrollable-content" style="margin: 20px 0px 20px 0px;">{{ field }}</div></td>
                        {% endfor %}
                        <td>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script src="../../static/jobs_created.js"></script>
</body>
</html>