main_project/blueprints/professor/__init__.py
from .routes import professor_bp

main_project/blueprints/professor/routes.py
from flask import Flask, render_template, request, redirect, url_for, session, Blueprint,current_app,g
from flask_mysqldb import MySQL
from flask_bcrypt import Bcrypt
import random
from main_project import bcrypt
from sqlalchemy import create_engine, text
from flask import session, redirect, url_for, render_template_string




professor_bp = Blueprint('professor_bp', __name__,template_folder='templates',static_url_path='/static',static_folder='static')

#Authentication Check
@professor_bp.before_request
def login_required():
    if 'email' not in session:
        # Redirect to the Google OAuth flow if the user is not authenticated
        return redirect(url_for('auth_bp.google',user_type='professor'))


def get_db_connection():
    engine = create_engine('mysql://oceoAdmin:oceoAdmin@localhost/oceo_management')
    print("Engine created")
    return engine.connect()

def check_authorization(faculty_id,job_id):
    cursor =get_db_connection()
    #check if job_id is present in job table
    result=cursor.execute(text(f"SELECT faculty_id FROM job WHERE job_id = {job_id} ;"))
    if result.rowcount == 0:
        cursor.close()
        return False 
    faculty_id_of_job = result.fetchone()[0]
    cursor.close()
    if faculty_id != faculty_id_of_job:
        return False
    return True




# ------------- START OF PROF --------------------------------------------------------------------------

@professor_bp.route('', methods=['GET', 'POST']) # professor homepage
def after_login_professor():
    if "faculty_id" in session :
        if request.method == 'POST':
            testvar = request.form['submit_button']
            match testvar:
                case 'personal_info':
                    return redirect(url_for('professor_bp.professor_personal_info'))
                case 'jobs_created':
                    return redirect(url_for('professor_bp.professor_jobs_created'))
                case 'timecard_for_review':
                    return redirect(url_for('professor_bp.professor_timecard_for_review'))
                case 'logout':
                    return redirect(url_for('professor_bp.professor_logout'))
                case _:
                    return render_template('professor/after_login.html')
        cursor =get_db_connection()
        faculty_id = session['faculty_id']
        faculty_name = cursor.execute(text(f"SELECT first_name FROM faculty WHERE faculty_id = {faculty_id};")).fetchall()[0][0]
        cursor.close()
        return render_template('professor/after_login.html', faculty_name=faculty_name)
    else:
        return redirect(url_for('auth_bp.errorpage'))

@professor_bp.route('/personal_info', methods=['GET', 'POST'])
def professor_personal_info():
    if "faculty_id" in session:
        if request.method == 'POST':
            if request.form['submit_button'] == 'Update Profile':
                return redirect(url_for('professor_bp.professor_personal_info_change'))
            elif request.form['submit_button'] == 'Change Password':
                return redirect(url_for('professor_bp.professor_change_password'))
            
        cursor =get_db_connection()
        faculty_id = session['faculty_id']
        
        fetched_data = cursor.execute(text(f"SELECT * FROM faculty WHERE faculty_id = {faculty_id};")).fetchall()
        cursor.close()
        return render_template('professor/personal_info.html', professor_data=fetched_data)
    else:
        return redirect(url_for('auth_bp.errorpage'))
    
@professor_bp.route('/update_profile', methods=['GET', 'POST'])
def professor_personal_info_change():
    if "faculty_id" in session:
        if request.method == 'POST':
            faculty_id = session['faculty_id']
            first_name = request.form.get('first_name')
            middle_name = request.form.get('middle_name')
            last_name = request.form.get('last_name')
            dept_name = request.form.get('department_name')
            voip_id = request.form.get('voip_id')
            cursor =get_db_connection()
            cursor.execute(text(f"UPDATE faculty SET first_name = '{first_name}', middle_name = '{middle_name}', last_name = '{last_name}', dept_name = '{dept_name}', voip_id = {voip_id} WHERE faculty_id = {faculty_id}"))
            cursor.commit()

            if 'image' in request.files:
                image = request.files['image']
                image_data = image.read()
                cursor.execute(text(f"UPDATE faculty SET image = {image_data} WHERE faculty_id = {faculty_id};"))
                cursor.commit()
            
            cursor.close()
            return redirect(url_for('professor_bp.professor_personal_info'))
        cursor =get_db_connection()
        faculty_id = session['faculty_id']
        
        fetched_data = cursor.execute(text(f"SELECT * FROM faculty WHERE faculty_id = {faculty_id};")).fetchall()
        cursor.close()
        return render_template('professor/personal_info_change.html', professor_data=fetched_data)
    else:
        return redirect(url_for('auth_bp.errorpage'))

@professor_bp.route('/change_password', methods=['GET', 'POST'])
def professor_change_password():
    if "faculty_id" in session:
        if request.method == 'POST':
            faculty_id = session['faculty_id']
            cursor =get_db_connection()
            old_password = request.form.get('old_password')
            new_password = request.form.get('new_password')
            confirm_password = request.form.get('confirm_password')
            hashed_password = cursor.execute(text(f"SELECT password FROM faculty WHERE faculty_id = {faculty_id};")).fetchone()[0]
            cursor.close()
            if bcrypt.check_password_hash(hashed_password, old_password):
                if new_password == confirm_password:
                    new_hashed_password = bcrypt.generate_password_hash(new_password).decode("utf-8")
                    cursor =get_db_connection()
                    cursor.execute(text(f"UPDATE faculty SET password = '{new_hashed_password}' WHERE faculty_id = {faculty_id};"))
                    cursor.commit()
                    cursor.close()
                    return redirect(url_for('professor_bp.professor_personal_info'))
                else:
                    return redirect(url_for('auth_bp.errorpage'))
            else:
                return redirect(url_for('auth_bp.errorpage'))
        return render_template('professor/change_password.html')
    else:
        return redirect(url_for('auth_bp.errorpage'))

@professor_bp.route('/jobs_created', methods=['GET', 'POST'])
def professor_jobs_created():
    if "faculty_id" in session:
        if request.method == 'POST':
            if request.form['submit_button'] == 'job_page':
                job_id = request.form['job_id']
                return redirect(url_for('professor_bp.professor_job_page', job_id=job_id))
            
        
        cursor =get_db_connection()
        faculty_id = session['faculty_id']
        result=cursor.execute(text(f"SELECT job_id,job_type,job_description,pay_per_hour,start_date,end_date,is_available FROM job WHERE job.faculty_id = {faculty_id};"))
        job_data = result.fetchall()
        
        column_names =['job_id','job_type','job_description','pay_per_hour','start_date','end_date','is_available']
        cursor.close()
        return render_template('professor/jobs_created.html', job_data=job_data, job_head=column_names)
    else:
        return redirect(url_for('auth_bp.errorpage'))

@professor_bp.route('/add_job', methods=['GET', 'POST'])
def professor_add_job():
    if "faculty_id" in session:
        if request.method == 'POST':
            faculty_id = session['faculty_id']
            job_type = request.form.get('job_type')
            job_description = request.form.get('job_description')
            min_qualifications = request.form.get('minimum_qualification')
            job_criteria = request.form.get('job_criteria')
            prerequisites = request.form.get('prerequisites')
            additional_info = request.form.get('additional_information')
            pay_per_hour = request.form.get('pay_per_hour')
            no_of_positions = request.form.get('number_of_positions')
            start_date = request.form.get('start_date')
            end_date = request.form.get('end_date')
            tenure = request.form.get('tenure')
            application_deadline = request.form.get('application_deadline')
            is_position_open = 1
            cursor =get_db_connection()
            result=cursor.execute(text("SELECT count(*) FROM job"))
            total_count = result.fetchone()[0]
            if total_count == 0:
                job_id = random.randint(12345678, 29999999)
            else:
                
                max_id = cursor.execute(text("SELECT MAX(job_id) FROM job")).fetchone()[0]
                job_id = max_id + 1

            cursor.execute(text(f"INSERT INTO job (job_id, job_type, job_description, min_qualifications, job_criteria, prerequisites, additional_info, pay_per_hour, no_of_positions, start_date, end_date, tenure, faculty_id, is_available, application_deadline) VALUES ({job_id}, '{job_type}', '{job_description}', '{min_qualifications}', '{job_criteria}', '{prerequisites}', '{additional_info}', {pay_per_hour}, {no_of_positions}, '{start_date}', '{end_date}', '{tenure}', {faculty_id}, {is_position_open}, '{application_deadline}');"))
            cursor.commit()
            if job_type == 'ADH':
                course_id = request.form.get('course_id')
                course_name = request.form.get('course_name')
                cursor.execute(text(f"INSERT INTO adh (job_id, course_id, course_name) VALUES ({job_id}, '{course_id}', '{course_name}');"))
                cursor.commit()
            elif job_type == 'PAL':
                subjects_to_teach = request.form.get('subjects_to_teach')

main_project/templates/professor/add_job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add a Job</title>
    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
    <!-- <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet"> -->
    <link rel="stylesheet" href="../../static/newuser.css">
    <link rel="stylesheet" href="../../static/sidebar.css">
    <!-- <link rel="stylesheet" href="../../static/jobs_created.css"> -->
</head>

<body>
    <div id="professor-sidebar">
        <div class="menu-icon" onclick="toggleMenu()">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <!-- professor sidebar -->
        <div id="sidebar" class="sidebar">
            <h2>Dashboard</h2>
            <a href="/professor">Home Page</a><br>
            <a href="/professor/personal_info">Personal Info</a>
            <!-- <button onclick="toggleSubLinks()"></button> -->
            <br>
            <div class="sub-links">
                <a href="/professor/change_password">Change Password</a><br>
                <a href="/professor/update_profile">Personal Info Change</a><br>
            </div>
            <a href="/professor/jobs_created" >Jobs Created</a><br>
            <div class="sub-links">
                <a href="/professor/add_job">Create New Jobs</a><br>
            </div>
            <a href="/professor/timecard_for_review">Timecards for review</a><br>
            <a href="/professor/logout">Logout</a><br>
        </div>
    </div>

    <h1 style="padding-top: 50px; text-align:center; border: 1px #e9e9e9;">Add a Job</h1>
    <form action="/professor/add_job" method="post">
        <label for="job_type">Job type:</label><br>
        <input type="radio" id="ADH" name="job_type" value="ADH" onclick="toggleCourseFields()" required> ADH <br>
        <input type="radio" id="PAL" name="job_type" value="PAL" onclick="toggleCourseFields()" required> PAL <br>
        <input type="radio" id="others" name="job_type" value="other" onclick="toggleCourseFields()" required> Others <br>
        <div id="course-fields">
            <label for="course_id">Course ID:</label><br>
            <input type="text" id="course_id" name="course_id" placeholder="Enter Course ID"><br>
            <label for="course_name">Course Name:</label><br>
            <input type="text" id="course_name" name="course_name" placeholder="Enter Course Name"><br>
        </div>
        <div id="subject_to_teach">
            <label for="subject_to_teach">Subjects To Teach:</label><br>
            <input type="text" id="subject_to_teach1" name="subjects_to_teach" placeholder="Enter Subjects To Teach"><br>
        </div>
        <div id="role_name">
            <label for="role_name">Role Name:</label><br>
            <input type="text" id="role_name1" name="role_name" placeholder="Enter Role Name"><br>
        </div>

        <label for="job_description">Job Description:</label><br>
        <textarea id="job_description" name="job_description" placeholder="Enter Job Description" required></textarea><br>
        <label for="minimum_qualification">Minimum qualification:</label><br>
        <input type="text" id="minimum_qualification" name="minimum_qualification" placeholder="Enter Minimum CPI required for the position" required><br>
        <label for="job_criteria">Job Criteria:</label><br>
        <textarea id="job_criteria" name="job_criteria" placeholder="Enter Job Criteria" required></textarea><br>
        <label for="prerequisites">Prerequisites:</label><br>
        <textarea id="prerequisites" name="prerequisites" placeholder="Enter prerequisite courses to be done before applying for position" required></textarea><br>
        <label for="additional_information">Additional Information:</label><br>
        <textarea id="additional_information" name="additional_information" placeholder="Enter Additional Information" required></textarea><br>
        <label for="pay_per_hour">Pay per hour:</label><br>
        <input type="text" id="pay_per_hour" name="pay_per_hour" placeholder="Enter Pay per Hour" required><br>
        <label for="number_of_positions">Number of Positions:</label><br>
        <input type="text" id="number_of_positions" name="number_of_positions" placeholder="Enter Number of Positions" required><br>
        <label for="start_date">Start Date:</label><br>
        <input type="date" id="start_date" name="start_date" required><br>
        <label for="end_date">End Date:</label><br>
        <input type="date" id="end_date" name="end_date" required><br>
        <label for="tenure">Tenure:</label><br>
        <input type="text" id="tenure" name="tenure" placeholder="Enter Tenure" required><br>
        <label for="application_deadline">Application Deadline:</label><br>
        <input type="date" id="application_deadline" name="application_deadline" required><br>
        <input type="submit" id="submit_button" value="Submit Application">
    </form>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- <script src="../../static/personal_info.js"></script> -->
    <script>
        function toggleCourseFields() {
            var adhRadioBtn = document.getElementById('ADH');
            var courseFields = document.getElementById('course-fields');
            var palRadioBtn = document.getElementById('PAL');
            var subject_to_teach = document.getElementById('subject_to_teach');
            var role_name = document.getElementById('role_name');

            if (adhRadioBtn.checked) {
                courseFields.style.display = 'block';
                subject_to_teach.style.display = 'none';
                role_name.style.display = 'none';
            } else if (palRadioBtn.checked) {
                subject_to_teach.style.display = 'block';
                courseFields.style.display = 'none';
                role_name.style.display = 'none';
            } else {
                role_name.style.display = 'block';
                courseFields.style.display = 'none';
                subject_to_teach.style.display = 'none';
            }
        }

        function toggleSubmitButton() {
            var job_type = document.querySelector('input[name="job_type"]:checked').value;
            var course_id = document.getElementById("course_id").value.trim();
            var course_name = document.getElementById("course_name").value.trim();
            var subject_to_teach = document.getElementById("subject_to_teach1").value.trim();
            var role_name = document.getElementById("role_name1").value.trim();
            var job_description = document.getElementById("job_description").value.trim();
            var minimum_qualification = document.getElementById("minimum_qualification").value.trim();
            var job_criteria = document.getElementById("job_criteria").value.trim();
            var prerequisites = document.getElementById("prerequisites").value.trim();
            // var additional_information = document.getElementById("additional_information").value.trim();
            // above is optional
            var pay_per_hour = document.getElementById("pay_per_hour").value.trim();
            var number_of_positions = document.getElementById("number_of_positions").value.trim();
            var start_date = document.getElementById("start_date").value.trim();
            var end_date = document.getElementById("end_date").value.trim();
            var tenure = document.getElementById("tenure").value.trim();
            var application_deadline = document.getElementById("application_deadline").value.trim();
            
            var submitButton = document.getElementById("submit_button");

            if ( ((course_id && course_name) || subject_to_teach || role_name) && job_description && minimum_qualification && job_criteria && prerequisites && pay_per_hour && number_of_positions && start_date && end_date && tenure && application_deadline) {
                submitButton.classList.add("enabled");
            } else {
                submitButton.classList.remove("enabled");
            }
        }
        document.addEventListener("DOMContentLoaded", function() {
            var inputFields = document.querySelectorAll('input[type="text"], textarea, input[type="date"], input[type="radio"]');
            inputFields.forEach(function(field) {
                field.addEventListener("input", toggleSubmitButton);
            });
        });
    </script>
    <script src="../../static/sidebar.js"></script>
</body>
</html>

main_project/templates/professor/after_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Professor Login</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/professor/after_login.css">
</head>
<body>
    <header>
        <h1>Professor Portal</h1>
        <img src="../../static/Final_IITGN-Logo-symmetric-Black.png" class="logo" alt="IITGN logo">
    </header>

    <form action="{{url_for('professor_bp.after_login_professor')}}" method="post">
        <!-- <button class='btn' name="submit_button" value="personal_info" type="submit">Personal Info</button>
        <button class='btn' name="submit_button" value="jobs_available" type="submit">Jobs Available</button>
        <button class='btn' name="submit_button" value="applied_jobs" type="submit">Applied Jobs</button>
        <button class='btn' name="submit_button" value="logout" type="submit">Logout</button>
         -->
        <div class="container">
            <h2>Welcome, {{faculty_name}}!</h2>
            <button class='btn' name="submit_button" value="personal_info" type="submit">Personal Information</button>
            <button class='btn' name="submit_button" value="jobs_created" type="submit">Jobs created</button>
            <!-- <button class='btn' name="submit_button" value="applications" type="submit">Applications</button> -->
            <button class='btn' name="submit_button" value="timecard_for_review" type="submit">Timecards for review</button>
            <button class='btn' name="submit_button" value="logout" type="submit">Logout</button>
        </div>
    </form>
    <footer>
        <p>&copy; 2024, DataWeavers, CS432 Databases, IIT Gandhinagar, Gujarat, India</p>
    </footer>
    <script src="../../static/professor/after_login.js"></script>
</body>
</html>

main_project/templates/professor/approved_applications.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Approved Applications</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/jobs_created.css">
</head>


<body>     
    <div class="menu-icon" onclick="toggleMenu()">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <!-- professor sidebar -->
    <div id="sidebar" class="sidebar">
        <h2>Dashboard</h2>
        <a href="/professor">Home Page</a><br>
        <a href="/professor/personal_info">Personal Info</a>
        <!-- <button onclick="toggleSubLinks()"></button> -->
        <br>
        <div class="sub-links">
            <a href="/professor/change_password">Change Password</a><br>
            <a href="/professor/update_profile">Personal Info Change</a><br>
        </div>
        <a href="/professor/jobs_created" >Jobs Created</a><br>
        <div class="sub-links">
            <a href="/professor/add_job">Create New Jobs</a><br>
        </div>
        <a href="/professor/timecard_for_review">Timecards for review</a><br>
        <a href="/professor/logout">Logout</a><br>
    </div>

    
    <div id="main-content-above" class="main-content-above">
        <!-- <p type="hidden">For space above the main form</p> -->
    </div>

    <div id="main-content" class="main-content table-container">
        <h1 style="padding-top: 50px; text-align:center; border: 1px #e9e9e9;" >Applications</h1>
        <table class="main-content-table">
            <thead class="main-content-table-head">
                <tr class="main-content-table-head-row">
                    <th>Job ID</th>
                {% for columnName in application_head %}
                    <th>{{ (columnName.replace("_", " ")).capitalize() }}</th>
                {% endfor %}
                </tr>
            </thead>
            <tbody class="main-content-table-body" >
                {%set i = namespace(value=0)%}
                {% for job in application_data %}
                {% if i.value % 2 == 0 %}
                <tr class="main-content-table-body-row">
                {% else %}
                <tr class="main-content-table-body-row" style="background-color: #f2f2f2;">
                {% endif %}
                {%set i.value = i.value + 1%}

                    <td>{{ job_id }}</td>
                    {% for field in job %}
                        <td>{{ field }}</td>
                    
                    {% endfor %}
                    <td>
                        <form action="/professor/approved_applications/{{job_id}}" method="post">
                            <input type="hidden" name="application_id" value="{{ job[0]}}">
                            <input type="hidden" name="job_id" value="{{ job_id }}">
                            <button type="submit" name="submit_button" value="remove" class="update-profile">remove</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="../../static/jobs_created.js"></script>
</body>
</html>

main_project/templates/professor/assign_mentees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assign Mentees</title>
</head>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
<style>
    body {
        font-family: 'Open Sans', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f2f2f2;
    }
    
    form {
        max-width: 500px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }
    
    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
    }
    
    input[type="text"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 20px;
    }
    
    input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }
    
    input[type="submit"]:hover {
        background-color: #45a049;
    }
    
    button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }
    
    button:hover {
        background-color: #45a049;
    }
    
    #additional-fields {
        margin-bottom: 20px;
    }
    
    button {
        margin-top: 20px;
    }
    
    button:hover {
        background-color: #45a049;
    }
    
    button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }
    
    button:hover {
        background-color: #45a049;
    }
    
    button {
        margin-top: 20px;
    }
    
    button:hover {
        background-color: #45a049;
    }
    
</style>
<body>
    <form action="/professor/assign_mentees/{{job_id}}&{{roll_number}}" method="post">
        <!-- <label for="mentor_roll_number">Mentor Roll Number:</label> -->
        <!-- <input type="text" id="mentor_roll_number" name="mentor_roll_number" value="add mentor roll number"><br><br> -->
        
        
        <label for="mentee_roll_number">Roll Number:</label>
        <input type="text" id="mentee_roll_number" name="mentee_roll_number" placeholder="add roll number"><br><br>
        
        <label for="first_name">First Name:</label>
        <input type="text" id="first_name" name="first_name" placeholder="add first name"><br><br>

        <label for="middle_name">Middle Name:</label>
        <input type="text" id="middle_name" name="middle_name" placeholder="add middle name"><br><br>

        <label for="last_name">Last Name:</label>
        <input type="text" id="last_name" name="last_name" placeholder="add last name"><br><br>

        <div id="additional-fields"></div><br>
        
        <button type="button" onclick="addAdditionalFields()">Add Additional Fields</button><br><br>
        <button type="submit" name="submit_button" value="assign_mentees">Assign</button><br>
    </form>

    <script>
        function addAdditionalFields() {
            var additionalFieldsDiv = document.getElementById("additional-fields");
            
            // var mentorRollNumberInput = document.createElement("input");
            // mentorRollNumberInput.type = "text";
            // mentorRollNumberInput.name = "mentor_roll_number";
            // mentorRollNumberInput.value = "add mentor roll number";
            // additionalFieldsDiv.appendChild(mentorRollNumberInput);

            var rollNumberInput = document.createElement("input");
            rollNumberInput.type = "text";
            rollNumberInput.name = "roll_number";
            rollNumberInput.placeholder = "add roll number";
            additionalFieldsDiv.appendChild(rollNumberInput);

            var firstNameInput = document.createElement("input");
            firstNameInput.type = "text";
            firstNameInput.name = "first_name";
            firstNameInput.placeholder = "add first name";
            additionalFieldsDiv.appendChild(firstNameInput);

            var middleNameInput = document.createElement("input");
            middleNameInput.type = "text";
            middleNameInput.name = "middle_name";
            middleNameInput.placeholder = "add middle name";
            additionalFieldsDiv.appendChild(middleNameInput);

            var lastNameInput = document.createElement("input");
            lastNameInput.type = "text";
            lastNameInput.name = "last_name";
            lastNameInput.placeholder = "add last name";
            additionalFieldsDiv.appendChild(lastNameInput);

            var breakLine = document.createElement("br");
            additionalFieldsDiv.appendChild(breakLine);
            
            // var assignButton = document.createElement("button");
            // assignButton.type = "button";
            // assignButton.textContent = "Assign";
            // additionalFieldsDiv.appendChild(assignButton);

        }
    </script>
</body>
</html>

main_project/templates/professor/professor.html
<!DOCTYPE html>
<html>
<head>
    <title>Professor Login Page</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Open Sans', sans-serif;
            background-color: #f2f2f2;
        }
        
        h1 {
            text-align: center;
            color: #333;
        }
        
        form {
            max-width: 300px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        label {
            display: block;
            margin-bottom: 10px;
            color: #333;
        }
        
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        
        input[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
        input[type="submit"]:hover {
            background-color: #45a049;
        }
                
        .new-user-button {
            width: 100%;
            padding: 10px;
            background-color: #ccc;
            color: #333;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            margin-top: 10px;
        }
        
        .new-user-button:hover {
            background-color: #ddd;
        }
    </style>
</head>
<body>
    <h1>Enter Login Details</h1>
    <form action="{{ url_for('after_login_student') }}" method="post">
        <label for="email">Professor Email:</label>
        <input type="email" id="email" name="email" required><br><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>